// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nizbgqmmyfxqftrcgdjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pemJncW1teWZ4cWZ0cmNnZGpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTIyODksImV4cCI6MjA3Mjk4ODI4OX0.wIiNAPCkw5SgGmtJj-0Te0ZcdbXnWYFTyByKlraUEQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});